server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${properties.mysql.username}
    url: ${properties.mysql.url}
    password: ${properties.mysql.password}

  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

  redis:
    host: ${properties.redis.host}
    port: ${properties.redis.port}

  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${java.oauth.kakao.clientId}
            redirect-uri: ${java.oauth.kakao.redirectUri}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    rog:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace

file:
  path: C:/workspace/planto/upload/

app:
  firebase-configuration-file: ./serviceAccountKey.json
  firebase-bucket: planto-e2910.appspot.com

